// Generated by CoffeeScript 1.9.3
var createIcon, createIcons, dimFactory, elbow, lightFactory, loc;

loc = void 0;

elbow = function(d, i) {
  "M" + d.source.y + "," + d.source.x;
  return +"H" + d.target.y + "V" + d.target.x;
};

$(function() {
  var parts, svg, tree, url;
  url = window.parent.location.href;
  parts = url.split('/');
  loc = parts[parts.length - 1];
  if (loc === "d3testing.html") {
    tree = d3.layout.tree().separation(function(a, b) {
      return 1;
    }).children(function(d) {
      return d.children;
    }).size(960, 500);
    svg = d3.select("#paper").attr("width", 960).attr("height", 500).append("g");
    return d3.json("tree.json", function(err, json) {
      var link, node, nodes;
      if (err) {
        throw err;
      }
      nodes = tree.nodes(json);
      link = svg.selectAll('.link').data(tree.links(nodes)).enter().append("path").attr('class', 'link').attr('d', elbow);
      return node = svg.selectAll('.node').data(nodes).enter().append('g').attr('class', 'node').attr("transform", function(d) {
        return "translate(" + d.y + "," + d.x + ")";
      });
    });
  }
});

lightFactory = function(icon) {
  return function() {
    return icon.attr({
      fill: '#fff'
    });
  };
};

dimFactory = function(icon) {
  return function() {
    return icon.attr({
      fill: '#000'
    });
  };
};

createIcon = function(name, href) {
  var paper;
  paper = Snap("#" + name + "-icon");
  return Snap.load("/imgs/" + name + "-icon.svg", function(f) {
    var icon;
    icon = f.select('#icon');
    paper.append(icon);
    return $("#" + name + "-icon").hover(lightFactory(icon)).mouseleave(dimFactory(icon)).click(function() {
      return window.location.href = href;
    });
  });
};

createIcons = function(list) {
  var icon, j, len, results;
  results = [];
  for (j = 0, len = list.length; j < len; j++) {
    icon = list[j];
    results.push(createIcon(icon.name, icon.href));
  }
  return results;
};

$(function() {
  if (loc !== "d3testing.html") {
    return createIcons([
      {
        name: "iare",
        href: "/"
      }, {
        name: "cluster",
        href: "/cluster.html"
      }, {
        name: "cal",
        href: "/cal.html"
      }, {
        name: "news",
        href: "/news.html"
      }
    ]);
  }
});
