// Generated by CoffeeScript 1.9.3
$(function() {
  var $cal, loc, parts, url;
  url = window.parent.location.href;
  parts = url.split('/');
  loc = parts[parts.length - 1];
  if (loc === "cal.html") {
    return $cal = $("#cal").fullCalendar({
      aspectRatio: 1
    });
  }
});
