// Generated by CoffeeScript 1.9.3
var choose, close, internPopup, open, selectPopup;

open = function(wrapper) {
  $(".popup.popup-wrapper").addClass('active');
  return $(".popup.popup-overlay").addClass('active');
};

close = function() {
  $(".popup.popup-wrapper").removeClass('active').html("");
  return $(".popup.popup-overlay").removeClass('active');
};

choose = function(type) {
  switch (type) {
    case "exit":
      return close;
    case "intern":
      return function() {
        close();
        return internPopup();
      };
    default:
      return close;
  }
};

internPopup = function() {
  open();
  return $.ajax({
    cache: false,
    url: "/editor-intern.html",
    success: function(content) {
      $(content).appendTo($(".popup.popup-wrapper"));
      $(".popup.popup-finish").click(function() {
        console.log($(".popup.editor > form").serialize());
        return close();
      });
      return $(".popup.popup-abort").click(function() {
        console.log("abort");
        return close();
      });
    }
  });
};

selectPopup = function() {
  var $wrapper, i, len, opt, options, text;
  text = $(".popup.popup-select").attr("data-options");
  options = $.parseJSON(text);
  options.push({
    text: "Avbryt",
    type: "exit"
  });
  open(false);
  $wrapper = $("<div>").addClass("popup popup-select");
  for (i = 0, len = options.length; i < len; i++) {
    opt = options[i];
    $("<div>").addClass("popup popup-select-option").html(opt.text).click(choose(opt.type)).appendTo($wrapper);
  }
  return $wrapper.appendTo($(".popup.popup-wrapper"));
};

$(function() {
  $("<div>").addClass("popup popup-overlay").appendTo($('body'));
  $("<div>").addClass("popup popup-wrapper").appendTo($('body'));
  $(".popup.popup-select").click(selectPopup);
  return $(".popup.popup-intern").click(internPopup);
});
