// Generated by CoffeeScript 1.9.3
var createIcon, createIcons, dimFactory, lightFactory;

lightFactory = function(icon) {
  return function() {
    return icon.attr({
      fill: '#fff'
    });
  };
};

dimFactory = function(icon) {
  return function() {
    return icon.attr({
      fill: '#000'
    });
  };
};

createIcon = function(name, href) {
  var paper;
  console.log("called");
  paper = Snap("#" + name + "-icon");
  return Snap.load("/imgs/" + name + "-icon.svg", function(f) {
    var icon;
    icon = f.select('#icon');
    paper.append(icon);
    return $("#" + name + "-icon").hover(lightFactory(icon)).mouseleave(dimFactory(icon)).click(function() {
      return window.location.href = href;
    });
  });
};

createIcons = function(list) {
  var i, icon, len, results;
  results = [];
  for (i = 0, len = list.length; i < len; i++) {
    icon = list[i];
    results.push(createIcon(icon.name, icon.href));
  }
  return results;
};

$(function() {
  var loc, parts, url;
  url = window.parent.location.href;
  parts = url.split('/');
  loc = parts[parts.length - 1];
  return createIcons([
    {
      name: "iare",
      href: "/"
    }, {
      name: "cluster",
      href: "/cluster.html"
    }, {
      name: "cal",
      href: "/cal.html"
    }
  ]);
});
